import cgen as C
test = C.cgen('test.c')
test.code.append(C.sysinclude('stdio.h'))
test.code.append(C.blank())
test.code.append(C.function('main', 'void',).add_param(C.variable('', '')))
body = C.block(innerIndent=3)
body.append(C.statement(C.variable('i, j, k', 'int')))
body.append(C.line(C.fcall('for').add_arg(r'i = 0, j = 0, k = 0; i < 4, k < 8, j < 10; i++')))
body1 = C.block(innerIndent=3)
body1.append(C.statement(C.fcall('printf').add_arg(r'"%d %d %d"').add_arg(r'i').add_arg(r'j').add_arg(r'k')))
body1.append(C.statement('j = j + 2'))
body1.append(C.statement('k = k + 3'))
body.code.append(body1)
test.code.append(body)
print(str(test))