import cgen as C
test = C.cgen('test.c')
test.code.append(C.sysinclude('stdio.h'))
test.code.append(C.blank())
test.code.append(C.function('main', 'void',).add_param(C.variable('', '')))
body = C.block(innerIndent = 3)
body.append(C.statement(C.variable('num', 'int')))
body.append(C.statement(C.fcall('printf').add_arg(r'"Enter an integer: "')))
body.append(C.statement(C.fcall('scanf').add_arg(r'"%d"').add_arg(r'&num')))
body.append(C.line(C.fcall('if').add_arg(r'num % 2 == 0')))
body1 = C.block(innerIndent=3)
body1.append(C.statement(C.fcall('printf').add_arg(r'"%d is even."').add_arg(r'num')))
body.code.append(body1)
body.append(C.line('else'))
body2 = C.block(innerIndent=3)
body2.append(C.statement(C.fcall('printf').add_arg(r'"%d is odd."').add_arg(r'num')))
body.code.append(body2)
test.code.append(body)
print(str(test))
